version: "3.7"
services:
  python:
    image: python
    container_name: scrocrix-hackerrank-python
    working_dir: /etc/local/hackerrank
    command: bash -c "while true; do sleep 1000; done"
    volumes:
      - .:/etc/local/hackerrank
  go:
    image: golang
    tty: true
    container_name: scrocrix-hackerrank-golang
    working_dir: /etc/local/hackerrank
    volumes:
      - .:/etc/local/hackerrank
